name: converter
description: "Instant Converter - Convert between multiple units instantly"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Navigation
  get: ^4.6.6
  
  # Responsive UI
  sizer: ^2.0.15
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # App Info
  package_info_plus: ^4.2.0
  
  # URL Launcher
  url_launcher: ^6.2.2
  
  # Icons
  cupertino_icons: ^1.0.2

  # Fonts
  google_fonts: ^6.1.0
  
  # Share
  share_plus: ^10.0.2

  # Date/Time & Timezones
  intl: ^0.19.0
  timezone: ^0.9.2

  # App icon
  flutter_launcher_icons: 0.14.4 


  flutter_native_splash: ^2.4.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  
